name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildWindows64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          for /L %%i in (1,1,3) do (
            haxelib install lime 8.1.3 && goto :continue || timeout /t 10
          )
          :continue
          for /L %%i in (1,1,3) do (
            haxelib install openfl 9.3.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel 5.5.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-addons 3.2.1 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-tools 1.5.1 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-ui 2.5.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxcpp 4.3.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxCodec 3.0.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install SScript 7.7.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxcpp-debug-server 1.2.4 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install tjson 1.4.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git flxanimate https://github.com/ShadowMario/flxanimate && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git linc_luajit https://github.com/superpowers04/linc_luajit && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hscript-ex 0.0.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hscript 2.5.0 && goto :continue || timeout /t 10
          )
      - name: Create Version Tag
        run: echo "%GITHUB_RUN_ID%" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id }}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows64Build
          path: export/release/windows/bin

  buildWindows32:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          for /L %%i in (1,1,3) do (
            haxelib install lime 8.1.3 && goto :continue || timeout /t 10
          )
          :continue
          for /L %%i in (1,1,3) do (
            haxelib install openfl 9.3.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel 5.5.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-addons 3.2.1 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-tools 1.5.1 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-ui 2.5.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxcpp 4.3.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxCodec 3.0.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install SScript 7.7.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxcpp-debug-server 1.2.4 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install tjson 1.4.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git flxanimate https://github.com/ShadowMario/flxanimate && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git linc_luajit https://github.com/superpowers04/linc_luajit && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hscript-ex 0.0.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hscript 2.5.0 && goto :continue || timeout /t 10
          )
      - name: Create Version Tag
        run: echo "%GITHUB_RUN_ID%" > VERSION
      - name: Compile
        run: haxelib run lime build windows -32 -D 32bits --app-version="4.0.0-${{ github.run_id }}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows32Build
          path: export/32bit/windows/bin

  buildHTML5:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          for /L %%i in (1,1,3) do (
            haxelib install lime 8.1.3 && goto :continue || timeout /t 10
          )
          :continue
          for /L %%i in (1,1,3) do (
            haxelib install openfl 9.3.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel 5.5.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-addons 3.2.1 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-tools 1.5.1 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install flixel-ui 2.5.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxcpp 4.3.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxCodec 3.0.2 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install SScript 7.7.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hxcpp-debug-server 1.2.4 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install tjson 1.4.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git flxanimate https://github.com/ShadowMario/flxanimate && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git linc_luajit https://github.com/superpowers04/linc_luajit && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hscript-ex 0.0.0 && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc && goto :continue || timeout /t 10
          )
          for /L %%i in (1,1,3) do (
            haxelib install hscript 2.5.0 && goto :continue || timeout /t 10
          )
      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION
      - name: Compile
        run: haxelib run lime build html5 --app-version="4.0.0-${{ github.run_id }}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: html5Build
          path: export/html5

